local M = {}

M.cmp_kind = {
  Class = "󰌗",
  Color = " ",
  Constant = "",
  Constructor = " ",
  Default = " ",
  Enum = "󰕘",
  EnumMember = " ",
  Event = " ",
  Field = "󰜢",
  File = "󰈙",
  Folder = " ",
  Function = " ",
  Interface = " ",
  Keyword = "󰌋",
  Method = "ƒ ",
  Module = "󰏗",
  Operator = "󰆕",
  Property = " ",
  Reference = "󰈇",
  Snippet = " ", -- " "," "
  Struct = "פּ ",
  Text = "󰉿",
  TypeParameter = "  ",
  Unit = "",
  Value = "󰎠",
  Variable = " ",
}

M.icons = {
  error = " ",
  warn = " ",
  info = "",
  hint = " ",
  code_action = "",
  test = "",
  docs = "",
  clock = "",
  calendar = " ",
  buffer = "󰀿",
  settings = " ",
  ls_inactive = "󰒎",
  ls_active = "󰒍",
  question = "",
  screen = "󰐯",
  dart = " ",
  config = " ",
  git = "",
  magic = " ",
  exit = "󰅚",
  repo = "",
  term = " ",
}

M.nvim_tree_icons = {
  default = "",
  symlink = "",
  git = {
    unstaged = "",
    staged = "",
    unmerged = "",
    renamed = "➜",
    untracked = "",
    deleted = "",
    ignored = "◌",
  },
  folder = {
    arrow_closed = "",
    arrow_open = "",
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
}

M.symbols_outline = {
  File = "󰈙",
  Module = "󰏗",
  Namespace = "󰅪",
  Package = "󰏗",
  Class = "󰌗",
  Method = "ƒ",
  Property = "",
  Field = "󰆨",
  Constructor = "",
  Enum = "󰕘",
  Interface = "󰜰",
  Function = "",
  Variable = "",
  Constant = "",
  String = "𝓐",
  Number = "#",
  Boolean = "⊨",
  Array = "󰅪",
  Object = "⦿",
  Key = "󰌋",
  Null = "NULL",
  EnumMember = "",
  Struct = "󰙅",
  Event = "",
  Operator = "󰆕",
  TypeParameter = "𝙏",
}

M.todo_comments = {
  FIX = "󰓙",
  TODO = " ",
  HACK = "󰂖",
  WARN = "󰒡",
  PERF = "󰓅",
  NOTE = "󰍪",
  ERROR = " ",
  REFS = "",
}

M.numbers = {
  "󰎥",
  "󰎨",
  "󰎫",
  "󰎲",
  "󰎯",
  "󰎴",
  "󰎷",
  "󰎺",
  "󰎽",
  "󰿫",
}

M.file_icons = {
  Brown = { "" },
  Aqua = { "" },
  LightBlue = { "", "" },
  Blue = { "", "", "", "", "", "", "", "", "", "", "", "", "" },
  DarkBlue = { "", "" },
  Purple = { "", "", "", "", "" },
  Red = { "", "", "", "", "", "" },
  Beige = { "", "", "" },
  Yellow = { "", "", "λ", "", "" },
  Orange = { "", "" },
  DarkOrange = { "", "", "", "", "" },
  Pink = { "", "" },
  Salmon = { "" },
  Green = { "", "", "", "", "", "󰌛" },
  LightGreen = { "", "", "", "󰡄" },
  White = { "", "", "", "", "", "" },
}

return M
